# Generated by Django 4.2.20 on 2025-04-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_alter_product_price_alter_product_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
            ],
        ),
    ]
